// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCI4JBXfy8uKU5S2i3k1V2JfaHFxF4AGxw',
    appId: '1:870702384009:web:39ecba7c67f5f19b261758',
    messagingSenderId: '870702384009',
    projectId: 'vega-71a00',
    authDomain: 'vega-71a00.firebaseapp.com',
    storageBucket: 'vega-71a00.appspot.com',
    measurementId: 'G-7Q442H4V3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9F7m5oKXZeSXX35J1rvGainbFGQnGMDI',
    appId: '1:870702384009:android:9db389b84a35b755261758',
    messagingSenderId: '870702384009',
    projectId: 'vega-71a00',
    storageBucket: 'vega-71a00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xIna6FdHfpDerPeYMH0n14ub4JYx91w',
    appId: '1:870702384009:ios:c1c19b641c6f6daa261758',
    messagingSenderId: '870702384009',
    projectId: 'vega-71a00',
    storageBucket: 'vega-71a00.appspot.com',
    iosBundleId: 'com.example.vega',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1xIna6FdHfpDerPeYMH0n14ub4JYx91w',
    appId: '1:870702384009:ios:c1c19b641c6f6daa261758',
    messagingSenderId: '870702384009',
    projectId: 'vega-71a00',
    storageBucket: 'vega-71a00.appspot.com',
    iosBundleId: 'com.example.vega',
  );
}
